apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: aksdemoacrgitopsflux.azurecr.io/azvote/azure-vote-front
    newTag: 8686bb451c3f26a9c2fc5e6cd0a12b8b1d2391de
  - name: aksdemoacrgitopsflux.azurecr.io/azvote/azure-vote-back
    newTag: 8686bb451c3f26a9c2fc5e6cd0a12b8b1d2391de
resources:
  - manifests.yaml