apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: aksdemoacrgitopsflux.azurecr.io/azvote/azure-vote-front
    newTag: eef9ca6bc356af4bc4501e24761dbcca79e804e7
  - name: aksdemoacrgitopsflux.azurecr.io/azvote/azure-vote-back
    newTag: eef9ca6bc356af4bc4501e24761dbcca79e804e7
resources:
  - manifests.yaml