apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: aksdemoacrgitopsflux.azurecr.io/azvote/azure-vote-front
    newTag: fc75086e493d25e8fb00e07a37c3bd93b616c2b3
  - name: aksdemoacrgitopsflux.azurecr.io/azvote/azure-vote-back
    newTag: fc75086e493d25e8fb00e07a37c3bd93b616c2b3
resources:
  - manifests.yaml